### ISSUE TITLE
No exam data for any module

### ISSUE THREAD

**Issue by advaypal** [nusmodifications/nusmods#263] opened 2016-06-26 16:52 UTC
Though the timetables have been updated to AY2016/2017, every module added to the timetable has no exam data. Not sure if this is a bug or incomplete data from IVLE.

![screen shot 2016-06-26 at 8 17 19 pm](https://cloud.githubusercontent.com/assets/13481303/16363579/4c13e612-3c01-11e6-8ae4-8028b561e791.png)

**Comment by xinan** [comment] 2016-06-26 16:57
Exam timetable is not yet released. Also, some of the modules are missing because CORS are not fully updated. Thanks for reporting. I'm closing this since the problem is not on our side.

**Closed by xinan** 2016-06-26 16:57 UTC
