### ISSUE TITLE
No prerequisite check in future AY

### ISSUE THREAD

**Issue by ThienDuc3112** [nusmodifications/nusmods#3768] opened 2024-08-13 02:44 UTC
### Describe the bug

The prerequisite check in planner don't work if course not in current year

### To Reproduce

1. Go to planner
2. Setting > graduating next year (or any options that isn't this year)
3. Pick any course with prerequisite (cs3223 for example) in next year
4. Course appear green even without prerequisite

### Expected behavior

Course check for prerequisite and appear yellow

### Desktop (please complete the following information):

- Browser [e.g. Chrome, Safari]

### Smartphone (please complete the following information):

- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 14.0.0]
- Browser [e.g. Stock browser, Safari]

**Comment by zwliew** [comment] 2024-08-13 12:17
Thanks for reporting! I'll close this as it's a duplicate of #3767.

**Closed by zwliew** 2024-08-13 12:17 UTC
Labels: bug
