### ISSUE TITLE
ModPlanner - Some of the prerequisites of some mods are not reflected properly

### ISSUE THREAD

**Issue by kieron560** [nusmodifications/nusmods#3297] opened 2021-06-28 10:24 UTC
NUSModPlanner would show that some modules lack the prerequisites from the previous sem (hence it would be highlighted in yellow), even though the modules are entered in the previous semesters. I think this is more of the prerequisites in the data is not updated properly or incorrect than an actual bug of the application.

For example for CS2040S, the prerequisites would include CS1101S, but it currently just states CS1010, and hence it shows yellow on NUSModPlanner. 

![image](https://user-images.githubusercontent.com/60651926/123621665-0ba70800-d83e-11eb-8a53-f9e81f741622.png)

**Comment by chrisgzf** [comment] 2021-06-30 17:44
Duplicate of https://github.com/nusmodifications/nusmods/issues/2788, closing for now.

**Closed by chrisgzf** 2021-06-30 17:44 UTC
