### ISSUE TITLE
Enable the site to have accounts registration. 

### ISSUE THREAD

**Issue by andreelim** [nusmodifications/nusmods#3284] opened 2021-06-19 14:54 UTC
I'm always frustrated when the timetable that I have planned magically disappears. It could be because I cleared my cache or search history and I would have to add in my modules again. 

### Describe the solution you'd like

A simple solution would be to have users register for an account so that the data keyed in (whether it is the timetable or the beta function module planner) can be synced into the account! By doing so, the timetable can be accessed easily on different computers as well.

**Comment by xingaporean** [comment] 2021-06-20 05:38
huh isn't that feature already available? this data is stored under your browser's local storage. it is likely an issue with your browser or what you did, not the app.

**Comment by chrisgzf** [comment] 2021-06-26 10:24
@xingaporean not really, we are still working on user accounts and backend timetable sync.

Nevertheless, thanks for raising this issue and this is a duplicate of #796, which we are working on and tracking at the moment. Will be closing this for now!

**Closed by chrisgzf** 2021-06-26 10:24 UTC
