### ISSUE TITLE
Timetable layout messed up with module titles

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#738] opened 2018-01-15 19:06 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Timetable cells are not aligned in horizontal mode with titles showing.

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

1. Ensure on horizontal mode
2. Turn on titles
3. Open http://modsn.us/hpH2N
4. See that the lessons in Tue is not aligned

![screen shot 2018-01-15 at 11 01 47 am](https://user-images.githubusercontent.com/1315101/34957789-e2df0ecc-f9e3-11e7-912c-2b8581501afe.png)

**What is the expected behavior?**

Lesson cells aligned properly.

**Further information**

- Which version of NUSMods are you currently using? 20180115-e5e55c6
- Did this work in NUSMods BEFORE the R release/redesign? Yes
- Did this work in NUSMods AFTER the R release/redesign? NA. Broke with the introduction of module titles
- Which browser and version are you using? E.g. Chrome 63
- Which device are you using? E.g. MacBook Pro 17
- Which operating system and version are you on? E.g. macOS 10.12.5

**Comment by ZhangYiJiang** [comment] 2018-01-15 23:40
This actually looks like it might be a duplicate of #519

**Comment by yangshun** [comment] 2018-01-15 23:40
Probably related 👍

**Comment by taneliang** [comment] 2018-01-17 02:00
Fixed in #746

**Closed by taneliang** 2018-01-17 02:00 UTC
Labels: bug, good first issue, timetable, user interface
