### ISSUE TITLE
For NSS2001 classes, the prereq tree shows that "at least 6" (at least all) instead of at least 1 of the prereq courses are required. These courses are not even from the same course, it should be "at least 1". This is preventing people from selecting NSS200I on edurec despite fulfilling a prereq as edurec is following NUSmods. Thank you for reviewing!

### ISSUE THREAD

**Issue by jiatrees** [nusmodifications/nusmods#3476] opened 2023-08-01 01:34 UTC
### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Desktop (please complete the following information):

- Browser [e.g. Chrome, Safari]

### Smartphone (please complete the following information):

- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 14.0.0]
- Browser [e.g. Stock browser, Safari]

**Comment by Fidget-Spinner** [comment] 2023-08-03 15:47
Hello! Thank you for taking the time to file a bug report. I think there's a slight misunderstanding, NUSMods follows CourseReg data, not the other way around! So any bugs that prevent you from selecting a mod due to wrong prerequisites should be reported to CourseReg instead.

Also, it seems that the issue is resolved https://nusmods.com/courses/NSS2001I/science-and-society . So I'm closing this issue! Thanks.

**Closed by Fidget-Spinner** 2023-08-03 15:47 UTC
