### ISSUE TITLE
"Help us improve this map" functionality not working

### ISSUE THREAD

**Issue by Prometheus-03** [nusmodifications/nusmods#3805] opened 2024-08-23 03:28 UTC
### To Reproduce

1. Go to Venues
2. Choose a venue which needs improvement
3. Click "Help us improve this map"
4. Click "Problem with venue data"
5. Set the floor number to a different number from existing and move the marker a little so that the submit button becomes clickable (this in itself is a small bug which should be fixed imo, as changing the floor number should have been sufficient to trigger this)
6. Press submit

### Expected behavior

My change should have been submitted

### Screenshots

I get this error message: 

> There was a problem submitting your feedback. Please try again later.

![image](https://github.com/user-attachments/assets/aae37bd0-6e33-4bc8-92e0-2c6e50f5ca20)

### Desktop (please complete the following information):

- OS: Windows 11 Pro 24H2
- Browser: Opera Developer 114.0.5249.0
- NUSMods R version: 20240817-59b78cc

### Additional context

I tested this for a few venues and both NUSSTU and my home wifi network, I also tested this on mobile with both mobile data and NUSSTU wifi.

**Comment by kavishsathia** [comment] 2024-08-23 10:01
Hi @Prometheus-03, I was able to reproduce this error. For any developers working on this, the following info could be helpful:

1. The venue feedback API is hosted on a separate API: `https://dev--nusmods-venue-github-hook--zwliew.autocode.dev/`, not `api.nusmods.com`.
2. The error happens when a preflight request is made to that API, likely because the relevant CORS headers are not included in the response.

**Comment by kaze-droid** [comment] 2024-08-24 04:33
Seems like a duplicate of issue #3769 caused by the service hosting venueFeedbackAPI being down

**Comment by Prometheus-03** [comment] 2024-08-25 06:27
Didn't notice since it was reported under a different name I guess

**Closed** 2024-08-28 05:00 UTC
