### ISSUE TITLE
Option to hide specific lecture/tutorial slots

### ISSUE THREAD

**Issue by flyingarticles** [nusmodifications/nusmods#3345] opened 2021-08-13 02:14 UTC
Sometimes certain lectures/tutorials for a module are pre-recorded, and having everything appear on the timetable makes it extremely cluttered.

There could be a small 'hide' button for every class in the timetable to hide it from view. This could either be completely hiding that class from the timetable, or simply greying it out/lowering the opacity on that specific class slot to differentiate it.

Here's a mockup:
![Untitled](https://user-images.githubusercontent.com/64209908/129295317-149c1e7f-da28-4e2c-8004-4677285af3da.png)

**Comment by li-kai** [comment] 2021-10-06 18:25
Thanks for taking your time to fill out the issue! This is a duplicate of #3334. 
Unfortunately we won't be doing this because it is out of scope of what a planner is. We advise using well designed calendar tools for your own modification to the timetable.

**Closed as completed by li-kai** 2021-10-06 18:25 UTC
Labels: duplicate
