### ISSUE TITLE
Timetable was using last year's info and no option to select year

### ISSUE THREAD

**Issue by evilmtv** [nusmodifications/nusmods#2102] opened 2019-08-20 11:31 UTC
### Describe the bug

- Used nusmods last year, when AY 2019/2020 started https://nusmods.com/ still redirected me to https://nusmods.com/timetable/sem-2 instead of sem 1's. I had to manually switch to sem-1 every time or type sem-1 in the URL.
- I realized the schedule wasn't tallying up with the announcements on luminus. Deleting the cookies for the site (which cleared all saved data) and adding back the module now shows the correct data for this AY. https://nusmods.com/ now redirects me to sem-1 correctly too.

### To Reproduce

N/A - Unable to as I did not save the cookies beforehand.

### Expected behavior

- Automatically update to next AY
OR
- Clear indication of the year for the data currently shown
- Ability to switch between AYs

### Screenshots

Old data:
![image](https://user-images.githubusercontent.com/19277738/63343357-5329f680-c380-11e9-971d-398c98b6b58b.png)
Minor note: Image is cropped and partially modified but doesn't misrepresent the data being shown

New data:
![image](https://user-images.githubusercontent.com/19277738/63343411-72288880-c380-11e9-8b05-bfb2b55052ec.png)
CS2102 and CP2201 current schedules are correctly shown

### Desktop (please complete the following information):

* OS: Windows 10
* Browser: Google Chrome
* Version: 76.0.3809.100 (Official Build) (64-bit)

### Additional context

Nil

**Comment by ZhangYiJiang** [comment] 2019-08-29 03:36
Thanks for reporting this. We are aware of the issue which is caused by our error reporting service being blocked by uBlock Origin and other adblockers. Unfortunately because this is caused by service worker this cannot be fixed by anything we do right now, although it won't happen again in the future because we've disabled our service worker.

**Closed by ZhangYiJiang** 2019-08-29 03:36 UTC
