### ISSUE TITLE
Red background in timetable

### ISSUE THREAD

**Issue by weiseng18** [nusmodifications/nusmods#3366] opened 2021-11-30 05:41 UTC
### Describe the bug

There is an additional red background in areas of the timetable. It appears in both horizontal and vertical modes. I only get this issue in Windows 10 Chrome but not in Ubuntu 20.04 Chrome.

The red background doesn't seem to be

- indication of module clashing
- indication of min workload not attained

so I suspect it might be a bug.

![image](https://user-images.githubusercontent.com/20338724/143991458-257cd7a2-fd64-47af-bfbe-e24b0b49a569.png)

![image](https://user-images.githubusercontent.com/20338724/143991323-a4899436-2a17-4c72-ad97-fd53a0b1499e.png)

I get the same issue in incognito mode as well.

![image](https://user-images.githubusercontent.com/20338724/143991740-6d3c46f9-8a2f-49e7-9ff5-9f17d91eadd5.png)

### To Reproduce

1. Go to [main page](https://www.nusmods.com) or directly to the timetable ([Sem 1](https://nusmods.com/timetable/sem-1) or [Sem 2](https://nusmods.com/timetable/sem-2))

### Expected behavior

There should not be an additional red background

### Screenshots

Added above

### Desktop (please complete the following information):

- OS: Windows 10
- Browser: Chrome
- Version: 96

### Smartphone (please complete the following information):

- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 14.0.0]
- Browser [e.g. Stock browser, Safari]

**Comment by chrisgzf** [comment] 2021-11-30 05:52
Hi there,

I added the exact same modules to the timetable but I can't seem to reproduce the bug.

![image](https://user-images.githubusercontent.com/4933577/143992865-d98e5f5b-67a3-4276-bcce-4ff6d8250bde.png)

I suspect it might be a device-specific problem on your windows machine. There are a few things you can try to help us see if it is indeed a NUSMods bug.

To check:
1. Any console errors? (right click anywhere on the page, click on "Inspect" > "Console")
2. Update your GPU drivers
3. Check if hardware acceleration is turned on or off in Chrome, and then toggle it to see if it fixes the issue

If you can reproduce the same bug on another device, and let me know the steps you take to do so, that would be ideal!

Thanks for reporting the bug!

**Comment by weiseng18** [comment] 2021-11-30 06:01
Thanks for the quick reply, it seems like turning off hardware acceleration fixes the issue.

For your reference, this was the console logs before I tried to turn off hardware acceleration:

![image](https://user-images.githubusercontent.com/20338724/143993928-dc24a508-d087-4ae0-8057-cb054c49f452.png)

Feel free to close this issue!

**Comment by chrisgzf** [comment] 2021-11-30 06:07
Yeap! Those are normal (the errors you see are due to your adblocker blocking some of the scripts we use to collect usage data / detect errors, etc.). Glad you were able to fix the issue.

Closing.

**Closed by chrisgzf** 2021-11-30 06:07 UTC
