### ISSUE TITLE
Undo history does not persist across page refreshes

### ISSUE THREAD

**Issue by flxffy** [nusmodifications/nusmods#2173] opened 2019-09-15 14:20 UTC
### Describe the bug

Undid the removal of a module, but it was still removed after the page was refreshed

### To Reproduce

1. Remove a module
2. Undo the removal
3. Refresh the page
4. The module removed in step 1 is gone

### Expected behavior

The module should still be there after the page is refreshed

### Screenshots

![ezgif-2-e8dd5a4440cc](https://user-images.githubusercontent.com/30753834/64922854-6ce71e00-d806-11e9-9d9c-6b4ee55c5eb8.gif)

### Desktop (please complete the following information):

* OS: macOS Mojave
* Browser: Brave
* Version: 0.68.132

**Comment by davidchoo12** [comment] 2019-09-16 08:43
Tested and confirmed bug
OS: Windows 10
Browser: Firefox 69.0

**Comment by ZhangYiJiang** [comment] 2019-09-19 18:39
Yup, this is a duplicate of #1254. Just fell off my radar while working on other things. We should fix that soon

**Closed by ZhangYiJiang** 2019-09-19 18:39 UTC
