### ISSUE TITLE
Create account such that students can view timetable on different devices

### ISSUE THREAD

**Issue by GDragonVIP** [nusmodifications/nusmods#1228] opened 2018-10-16 15:11 UTC
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Comment by li-kai** [comment] 2018-10-16 16:15
This is a duplicate of #796 which is in the works with #1104. Since this is a duplicate I'll close this issue. Thanks for opening the issue, if you could provide more details in the future that'd be great!

**Closed by li-kai** 2018-10-16 16:15 UTC
